/* Generated By:JavaCC: Do not edit this line. ejercicioConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ejercicioConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDHURACAN = 1;
  /** RegularExpression Id. */
  int NOMBREH = 2;
  /** RegularExpression Id. */
  int SHURACAN = 3;
  /** RegularExpression Id. */
  int FECHAHUR = 4;
  /** RegularExpression Id. */
  int LATITUD = 5;
  /** RegularExpression Id. */
  int LONGITUD = 6;
  /** RegularExpression Id. */
  int WINDSMAX = 7;
  /** RegularExpression Id. */
  int DIA = 8;
  /** RegularExpression Id. */
  int MES = 9;
  /** RegularExpression Id. */
  int ANIO = 10;
  /** RegularExpression Id. */
  int HORA = 11;
  /** RegularExpression Id. */
  int GUION = 12;
  /** RegularExpression Id. */
  int OCEANO = 13;
  /** RegularExpression Id. */
  int ESPACIO = 14;
  /** RegularExpression Id. */
  int COMA = 15;
  /** RegularExpression Id. */
  int LETRAS = 16;
  /** RegularExpression Id. */
  int NUMERO = 17;
  /** RegularExpression Id. */
  int TRACKENTRIES = 18;
  /** RegularExpression Id. */
  int PUNTO = 19;
  /** RegularExpression Id. */
  int LATI = 20;
  /** RegularExpression Id. */
  int LONG = 21;
  /** RegularExpression Id. */
  int IDENTR = 22;
  /** RegularExpression Id. */
  int TIPOH = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IDHURACAN>",
    "<NOMBREH>",
    "<SHURACAN>",
    "<FECHAHUR>",
    "<LATITUD>",
    "<LONGITUD>",
    "<WINDSMAX>",
    "<DIA>",
    "<MES>",
    "<ANIO>",
    "<HORA>",
    "<GUION>",
    "<OCEANO>",
    "<ESPACIO>",
    "<COMA>",
    "<LETRAS>",
    "<NUMERO>",
    "<TRACKENTRIES>",
    "\".\"",
    "<LATI>",
    "<LONG>",
    "<IDENTR>",
    "<TIPOH>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
  };

}
